### ISSUE TITLE
Deposit the repo on Zenodo to make this tutorial citable

### ISSUE THREAD

**Issue by hechth** [jorainer/xcmsTutorials#22]
It would be great if this tutorial could be referenced and cited - would it be possible to setup a mirror to zenodo so that the releases of this are automatically indexed with a DOI?

**Comment by jorainer** [comment]
Excellent idea! do you have experience with linking/adding github repos with zenodo?

**Comment by hechth** [comment]
Yeah it's pretty easy - we have our galaxy tools repo linked and that works fine. If your want we can arrange a quick call and I'll walk you through the process, it takes like 10 minutes if you have a zenodo account

**Comment by jorainer** [comment]
Let me first fix the workflow - using the new Bioconductor 3.19 release - then I'll for sure come back to you, thanks!

**Comment by jorainer** [comment]
Done: https://zenodo.org/records/11185521
